spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://notification_db_container:5434/notification_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

logging:
  level:
    "[org.springframework]": INFO
    java: DEBUG