services:
  customer_db:
    image: postgres:16
    container_name: customer_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer_db
    ports:
      - "5433:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
      - ./db_init/customer_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d customer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory_db:
    image: postgres:16
    container_name: inventory_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_db
    ports:
      - "5436:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
      - ./db_init/inventory_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  order_db:
    image: postgres:16
    container_name: order_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./db_init/order_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service-container
    depends_on:
      customer_db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer_db:5432/customer_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service-container
    depends_on:
      inventory_db:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory_db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  order-service:
    build:
      context: ./order-service
    container_name: order-service-container
    depends_on:
      order_db:
        condition: service_healthy
      inventory-service:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/order_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  customer_db_data:
  inventory_db_data:
  order_db_data: