spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://customer_db_container:5432/customer_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    "[org.springframework]": INFO
    java: DEBUG