spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://order_db_container:5433/order_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

logging:
  level:
    "[org.springframework]": INFO
    java: DEBUG