# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq-container
spring.rabbitmq.port=5672
spring.rabbitmq.username=projectuser
spring.rabbitmq.password=rabbitmqexam

# Logging Configuration
logging.level.org.springframework=INFO